"""Initial migration.

Revision ID: 8f52598cf558
Revises: 
Create Date: 2023-06-30 22:08:17.347600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f52598cf558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('configType', sa.String(), nullable=True),
    sa.Column('adsType', sa.String(), nullable=True),
    sa.Column('adsName', sa.String(), nullable=True),
    sa.Column('adsId', sa.String(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_ads__id'), 'ads', ['_id'], unique=False)
    op.create_table('boost-package',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('packageId', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('packageName', sa.String(), nullable=True),
    sa.Column('packageStar', sa.Integer(), nullable=True),
    sa.Column('pricing', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_boost-package__id'), 'boost-package', ['_id'], unique=False)
    op.create_table('boost-star',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('numberOfFollower', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_boost-star__id'), 'boost-star', ['_id'], unique=False)
    op.create_table('feeds',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('feedid', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('uniqueId', sa.String(), nullable=True),
    sa.Column('tiktokId', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('heart', sa.Integer(), nullable=True),
    sa.Column('video', sa.Integer(), nullable=True),
    sa.Column('avatarLarger', sa.String(), nullable=True),
    sa.Column('isNew', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('covers', sa.String(), nullable=True),
    sa.Column('hasFollowTiktok', sa.Boolean(), nullable=True),
    sa.Column('boostStars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_feeds__id'), 'feeds', ['_id'], unique=False)
    op.create_table('history-boost',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('boostStars', sa.Integer(), nullable=True),
    sa.Column('boostStarsId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_history-boost__id'), 'history-boost', ['_id'], unique=False)
    op.create_table('history-follow',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('feedId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_history-follow__id'), 'history-follow', ['_id'], unique=False)
    op.create_table('last-login',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_last-login__id'), 'last-login', ['_id'], unique=False)
    op.create_table('trackings',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('screenDisplayId', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('osCodename', sa.String(), nullable=True),
    sa.Column('osVersion', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('hardware', sa.String(), nullable=True),
    sa.Column('displayVersion', sa.String(), nullable=True),
    sa.Column('bundleId', sa.String(), nullable=True),
    sa.Column('versionCode', sa.String(), nullable=True),
    sa.Column('versionName', sa.String(), nullable=True),
    sa.Column('packageName', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('contentType', sa.String(), nullable=True),
    sa.Column('http_user_agent', sa.String(), nullable=True),
    sa.Column('http_host', sa.String(), nullable=True),
    sa.Column('http_accept_encoding', sa.String(), nullable=True),
    sa.Column('remote_port', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_trackings__id'), 'trackings', ['_id'], unique=False)
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('uniqueId', sa.String(), nullable=True),
    sa.Column('tiktokId', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('heart', sa.Integer(), nullable=True),
    sa.Column('video', sa.Integer(), nullable=True),
    sa.Column('avatarLarger', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('isNew', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('covers', sa.String(), nullable=True),
    sa.Column('hasFollowTiktok', sa.Boolean(), nullable=True),
    sa.Column('tokens', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_users__id'), 'users', ['_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users__id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trackings__id'), table_name='trackings')
    op.drop_table('trackings')
    op.drop_index(op.f('ix_last-login__id'), table_name='last-login')
    op.drop_table('last-login')
    op.drop_index(op.f('ix_history-follow__id'), table_name='history-follow')
    op.drop_table('history-follow')
    op.drop_index(op.f('ix_history-boost__id'), table_name='history-boost')
    op.drop_table('history-boost')
    op.drop_index(op.f('ix_feeds__id'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_boost-star__id'), table_name='boost-star')
    op.drop_table('boost-star')
    op.drop_index(op.f('ix_boost-package__id'), table_name='boost-package')
    op.drop_table('boost-package')
    op.drop_index(op.f('ix_ads__id'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
